import Image from 'next/image';
import Frontmatter from "@/components/Frontmatter.js";

import image from "./hero.jpg";
import promiseDiagram from "./promise-diagram.png";

export const frontmatter = {
    isPublished: true,
    title: "Understanding Promises in JavaScript",
    date: "2023-01-14",
    excerpt: "Let's talk about JavaScript promises.  We're going to do a deep dive using a very basic examples that build upon one and other, and explain how the system behaves.  Then we'll follow up with a real-world example using a public REST API.  By the end of this post you should have a solid understanding of the core concepts.",
    image,
    imageAlt: "Hero image",
    imageCredit: `Photo by <a href="https://unsplash.com/@cytonn_photography?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Cytonn Photography</a> on <a href="https://unsplash.com/photos/vWchRczcQwM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>`,
}

export default ({children}) => (<Frontmatter>{children}</Frontmatter>);

Promises were invented as a way for JavaScript to manage callback functions that are needed when performing some kind of long-running task.

> ‚úã Note: Promises remain an integral part of ES6 today, but the pattern of working directly with promises as described in this article is considered low-level, and is no longer widely used. As of ES7, it is recommended that you use `async` and `await`, instead.  

> That said, having a firm grasp of what promises do will give you a much better understanding of `async` and `await`, as these two keywords are built on top of promises.

# The problem

Imagine you have a webpage, and it needs to do something like:

* make a request to fetch some data that you want to show on the page.
* set a timer, then do something after it has elapsed.

What you don't want to do is make JavaScript wait until the response comes back, because it will make the webpage freeze.  And to put it mildly, users won't like that.

To get around this problem, JavaScript uses callback functions.  This is a common technique used in nearly all programming languages since long before the internet was a thing.

What's a callback function?  Consider this example using `setTimeout`, where we wait five seconds, then pop an alert modal with a message.

```JavaScript
setTimeout(
  () => alert("Your time is up!"), // üëà This is a callback function.
  5000
)
```

Suppose we have a function called `foo`, which needs to fetch a report that takes about 10 seconds to run, then returns some data.  For the purposes of this example, we'll return the number 5. 

```JavaScript
function foo(myCallback) {
  // Doing lots of stuff...

  // Very busy in here...

  // Yeah, it's gonna be a while. üòÖ

  // Ok, I'm done.  The answer is 5
  myCallback(5);
}
```

Here is how we would call `foo`:

```JavaScript
// Stuff to do, afterwords
function myCallback(data) {
  // Display the data

  console.log('Here is the data:', data);
}

// Now let's call foo
foo(myCallback);
```

This works pretty well for most cases, but what do you do if there's an error?  In this example there is no way to tell the callback function that something is wrong.  

One technique to get around this problem is to add a second parameter to `foo`, which is an error callback:

```JavaScript
function foo(successCallback, errorCallback) {
  // Fetching a very long report...

  // Yeah, it's taking a while...

  // Done! Now check for errors.
  if (someError) {
    errorCallback("Oh, no! üòØ");
  } else {
    successCallback(5);
  }
}
```

It's not a bad solution and it works well in simple cases, but what if you need to call `foo` again, right away?  Maybe you're processing requests in chunks, or you're working on a batch of data.  Or, `foo` could represent three different functions that have to be called, while initializing your page: load customer preferences, load a list of items to work with, and load the first item to be worked on.

```JavaScript
foo((data) => {
  console.log('First batch of data:', data);

  foo((data) => {
    console.log('Next batch of data data:', data);

    foo((data) => {
      console.log('And yet another batch of data data:', data);

      // Ad nausium...
    });
  });
});
```

Now imagine adding error callbacks into all that ‚òù, and you begin to see the limitations of this pattern.  Nested callbacks make your code hard to read and hard to maintain.

# Introducing promises

Promises have been around for a while now, but they haven't been a standard part of JavaScript until ES6.  So, how do they work?

Instead of requiring the caller to pass in callbacks, your funciton merely returns a promise.  For the purpose of our example, `foo` is going to do the following:

```JavaScript
function foo() {
  return Promise.resolve(5); // <-- More about this, later!
}
```

So, instead of requiring us to pass in success/error callback functions, `foo` now returns this new thing, called a `Promise`.

> NOTE: I'm not going to go into an explanation of how to create a new `Promise` object, because that pattern way too low-level, and it's well beyond the scope of this article.  I will explain what the `resolve` function does in just a sec.  

This `Promise` object behaves like a handle, and it helps you keep track of what's going on inside of `foo`.  Here is how we call `foo`:

```JavaScript
const myPromise = foo();
```

Okay, what do we do with a promise?

A `Promise` has three "states".  You can think of it kind of like a flowchart in the image below (reading left to right).

<Image src={promiseDiagram} alt="Diagram of a promise" className="indentedImage" />

Each `Promise` begins life in a "pending" state, which means the operation hasn't completed yet, and we're still waiting for it.  Once the operation has completed, the `Promise` is considered "settled", and it is in one of two states:

* <b>resolved:</b> the operation has successfully completed, and the results (if any) are ready to use.
* <b>rejected:</b> there was an error

A handy trick that I use to remember these three terms is to think of a lawsuit.  Two parties are in dispute and they go to court, and their case is "pending" trial.  At some point the judge will render a decision, and then the case is now "resolved".  If the judge doesn't like the case, or thinks it's not ready for trial, he or she can throw it out, and it's "rejected".  

The `Promise` class has two static methods for creating an instance of a <u>settled</u> `Promise`.  These are:

* <b>`Promise.resolve(...)`:</b> creates a new resolved (successful) promise.
* <b>`Promise.reject(...)`:</b> creates a new rejected (un-successful / error) promise.

Both of these static methods can take a single parameter, which is a data payload.  Either method takes the data you pass in, and wraps it in a new resolved/rejected promise.

These methods are useful in situations where you have a piece of data, and you need to wrap it in a promise.  Here is how you would create an error `Promise`:

```JavaScript
Promise.reject("Baby did a bad, bad thing.");
```

# Getting your results

Ok, so now you have a promise object, how do you get the results?

Every `Promise` object has a method, called `then`.  Your `then` method takes a callback, which JavaScript will call when the operation has finished.  Your callback can have a single parameter, which will contain the result.

You use it like this:

```JavaScript
foo().then(
  (data) => {
    console.log('Here is the data:', data);
  }
);
```

If you want to handle errors, Your `then` function can also take an error callback.  The error callback takes a single parameter which contains the error.  

Here is how you would use it:

```JavaScript
foo().then(
  (data) => {
    console.log('Here is the data:', data);
  },
  (error) => {
    console.error('There was an error calling foo:', error);
  }
);
```

# Advantages

Ok so on the surface, this looks like we're still using callbacks, but now we're adding <u>extra</u> steps.  How does this make things better?

Things are better for a number of reasons:

1. Calling your function is a lot cleaner.  You just pass in whatever parameters you need.  You don't care about the callbacks.
2. The `Promise` object can be passed around.  It can be stored and used later.  A function can return it as a result, and then the function's caller can worry about it.
3. Because of point #2, you can add callbacks when you actually need them, where you need them.

All of this means cleaner code.

```JavaScript
const myPromise = foo();

// I can do other stuff, while I'm waiting for foo to do its thing.

// Ok, now let's see the results.
myPromise.then((data) => console.log('Here is the data:', data));
```

Here's another example.  Function calls get wrapped inside function calls all the time, right?  

Imagine the actual call to `foo` is three levels deep.  You never see `foo`; instead, you call `funcOne`, and `funcOne` uses a library function called `funcTwo`, and it's `funcTwo` which actually handles the call to `foo`.  

If you were using straight callbacks, here is what you would have to code up:

```JavaScript
function funcOne(success, error) {
  funcTwo(success, error);
}

function funcTwo(success, error) {
  foo(success, error);
}
```

You would have to pass your callbacks down to every function in the call sequence.  Let's see how much cleaner things are if `foo` returns a `Promise`, instead:

```JavaScript
function funcOne() {
  return funcTwo;
}

function funcTwo() {
  return foo();
}
```

You didn't have to do anything special to either `funcOne` or `funcTwo`, they just do their thing and return whatever `foo` returns.  

The key is this: they don't need to know that `foo` was special in any way, whatsoever.  All they had to do was pass the return value back to the caller.

It's the caller's responsibility to deal with the result of `foo`:

```JavaScript
funcOne()
    .then((data) => console.log('Here is foo\'s result:', data));
```

See it yet?  By returning a `Promise`, no one has to worry about managing callbacks until they need to.  `foo` just does its job, and returns the promise.  Whoever called `foo` can deal with the promise, or they can pass it to another part of the code to handle it.

# Order of execution

So, this is pretty cool, but you might be wondering if there isn't a way to somehow return the answer back to the caller directly.  Do we really have to use a callback?  Why can't we just do something like this:

```JavaScript
const answer = foo().then(data => { 
    return data;
});

console.writeline("The answer is:", answer);
```

It's important to understand that when you call a `then` method, **JavaScript does not call your callback right away&mdash;ever**.  JavaScript <u>saves it for later</u>.  

You can't ever return the actual value back to the calling code.  

Why not?  

Because the calling code moves on with life and never waits around.  It's done.  It's gone.  It's made its contribution to the world, and now it's ready for the next life adventure.

Remember that JavaScript was built to run on a single thread.  So, the whole idea of promises is to help a single thread efficiently manage multiple tasks.  So, the thread executes the calling code, and lets it run to the end of whatever it was doing.  Only once it's completed will JavaScript check to see if any promises are settled, and begin calling their callbacks, one by one.

In conclusion, JavaScript doesn't wait for `foo` to complete&mdash;which is the entire point of promises.  The calling code doesn't have to block or wait for anything.  It hands that job off to the callback, and then it goes merrily on its way.  It's now the callback's job to finish things up.

Let's see an example of this.  What do you think happens if you run the following code?

```JavaScript
console.log('one');

foo().then(
  data => console.log('two', data)
);

console.log('three');
```

It's tempting to think that JavaScript will print the following:

```
one
two 5
three
```

But actually it prints this:

```
one
three
two 5
```

And the reason is that the arrow function doesn't get called until the calling code finishes.  When JavaScript sees `foo().then(...)`, it takes whatever function you pass in to your `then` method, and <u>saves it for later</u>.  

Even if the data is already there.  

The calling code does its thing, and only when it's finished will JavaScript go back and check if the promise is settled.

# Chaining promises

Ok, so let's talk about another powerful feature of promises, called "promise chaining".  

Remember the example from earlier, where we needed to call `foo` three times in a row? Promise chaining was invented to solve that very problem.  Basically, promise chaining means that whenever you have a promise you can add as many calls to `.then` as you like.  

Here is how it would look:

```JavaScript
foo
  .then((data) => {
    // Handle the data
  })
  .then(() => {
    // Here's another callback.  Call this one next...
  })
  .then((data) => {
    // And yet another callback.  Don't forget this one...
  });
```

Essentially, these callbacks get invoked one right after the other.  You can tack on as many as you like, and they will all get called after `foo` has completed.

Why would we want to do this?

There are lots of reasons, but probably the most important is when you have several nested function calls, and each one of them needs to perform some kind of post-processing step before returning the result to its caller.  

Let's look at an earlier example where `funcOne` calls `funcTwo`, and `funcTwo` calls `foo`:

```JavaScript
function funcOne() {
  return funcTwo
    .then(/* Do something after funcOne has finished */);
}

function funcTwo() {
  return foo()
    .then(/* process foo's result */);
}

funcOne()
  .then(/* Do something when funcOne, funcTwo, and foo are done */);
```

Ok, so what's going on here, exactly?

Three things.  Let's address them one by one.

## Every call to `.then` returns a new `Promise`

The first thing to learn is that every time you call a `then` method, it returns another brand-new promise. 

Always.  

Here's another example where I break things apart:

```JavaScript
const newPromise = foo()
  .then(data => console.log("First promise"));
//  ‚òù Here I'm calling then() on the *first* Promise object

newPromise // üëà And this is a second *brand-new* Promise object
  .then(() => console.log("Second promise"))
//  ‚òù This guy returns another promise, which JavaScript discards
```

There are three Promises in the code above.  

1. The first `Promise` is obtained when when I call `foo` (i.e., `foo`'s return value').  
2. The second `Promise` is returned when I call `.then()` on the first `Promise`.
3. The third is returned when I call `.then()` the second `Promise`, but it's unused and gets thrown away.

And that, in a nutshell, is why you can keep doing this:

```JavaScript
foo()
  .then( ... )
  .then( ... )
  .then( ... )
  .then( ... )
  .then( ... ); // I can keep doing this, all day!
```

So, that was the first thing.  Now let's talk about the second.  


## If your callback returns a value, it gets wrapped in the new promise.

If your success callback has a return value, your `then` method will wrap it in a resolved (i.e., successful) promise.  
```JavaScript
foo()
  .then(data => {
    return 6; // üëà This value gets wrapped into a 
              //     new *resolved* promise
  })
```

The same goes for your error callback.  The `then` method will consider the error handled, and will wrap anything you return from your error callback into a new resolved promise.

```JavaScript
foo()
  .then(
    () => { /* ... whatever */},
    (error) => {
      // I handle the error ... whatever

      return 6; // üëà And I return this new thing, which gets wrapped
                //     into a new *resolved* promise.
  })
```

It's important to note that the new `Promise` ‚òù is in a **resolved** state&mdash;not a rejected state.

And if you return nothing, you still get a `Promise`.  It just returns `undefined`.

```JavaScript
foo()
  .then(data => {
    // Do stuff with the data
    console.log("Here is the report:", 5);

    // And return nothing.  You still get a promise, and it's value 
    // is undefined.
  })
```

And finally, if either your success callback or your error callback return a `Promise` of their own, JavaScript will use that, instead.

```JavaScript
foo()
  .then(data => {
    // Do stuff with the data
    console.log("Here is the report:", 5);

    // üëá Call foo() again, and return a second promise.
    return foo();
  })
```

‚úã **Do not forget the `return` statement.**  You have to return the promise, explicitly.  You can't just call `foo`, or JavaScript will 
pretend your function is a "void function" (has no return value), and will return a brand-new promise, instead.

```JavaScript
foo()
  .then(data => {
    // Do stuff with the data
    console.log("Here is the report:", 5);

    foo(); // üëà This code still works, but foo's promise is
           //     not returned.  JavaScript will assume your
           //     function has NO RETURN VALUE, and will return
           //     an empty resolved promise, instead.
  })
```

So in summary, your success/error callbacks can return one of three things:

1. **nothing:** your `then` function will return a <u>resolved</u> promise, containing the value `undefined`.
2. **data of any kind:** your `then` function will return a <u>resolved</u> promise, containing the data (string, bool, number, object, etc.&mdash;whatever).
3. **a brand-new promise:** your `then` function will just pass it along in whatever state it happens to be in, whether pending, resolved, or rejected.

Now let's talk about the third and final aspect of promise chaining.

## The return value of one promise callback is passed as a parameter to the next callback

This is the most useful aspect of promise chaining, as it allows you to elegantly call multiple asynchronous operations one right after the other.  Remember that example at the start of this article where we needed to call `foo` three times in a row?

Here is how we would do it, using promises:

```JavaScript
foo
  .then((data) => {
    console.log("I've called foo once:", data);

    // Return the next Promise
    return foo();
  })
  .then((data) => {
    console.log("I've called foo twice:", data);

    // Return the next Promise
    return foo();
  })
  .then((data) => {
    console.log("I've called foo thrice:", data);

    // And now we're done.  There's no return statement, so
    // we return undefined.
  });
```

When you run the code above, it will print out this:

```
I've called foo once: 5
I've called foo twice: 5
I've called foo thrice: 5
```

But the really cool part is, I can use the result from one `.then()` and pass it to the next.  This allows all the `then` methods in a promise chain to work together.  

In this example, I am successively building up a string.  Each call to `then` adds a new color onto the end:

```JavaScript
Promise.resolve("red")
  .then(data => data + ", yellow")
  .then(data => data + ", green")
  .then(data => data + ", blue")
  .then(data => console.log(data));
```

The example above will print out this:

```
red, yellow, green, blue
```

Pretty cool, eh?

This feature is really important because, going back to the example where `funcOne` calls `funcTwo`, and `funcTwo` calls `foo`, each function needs to do some kind of post-processing step before returning the result.  <u>This happens frequently when making API calls</u>.  

Here is an example where we take the result from `foo` and display it on a webpage.  Each promise callback takes care of one specific aspect of the process:

```JavaScript
function funcOne() {
  return funcTwo()
    .then(response => {
      // Wrap the response in some HTML tags
      return `<div>${response}</div>`;
    });
}

function funcTwo() {
  return foo()
    .then(data => {
      // Format the result as a message string.
      return `The result is ${data}`;
    });
}

funcOne()
  .then(result => {
    // Display the result of the report on the page.
    document.querySelector(".report").innerHTML = result;
  });
```

# Error handling

Let's talk about error handling.  The `Promise` class's `then` method comes with some pretty robust error handling built in.  It allows you to catch an error right away and handle it.  

Here is a basic example:

```JavaScript
Promise.reject("BLAAAARG!! üò°üí¢")
  .then(
    () => console.log("Success--but we know that will never happen."),
    (error) => console.log("There was an attempt: " + error)
  )//  ‚òù Error handler ‚òù
```

The example above will print out this:

```
There was an attempt: BLAAAARG!! üò°üí¢
```

This system gives you a lot of flexibility in deciding how and when you want to handle errors.  If you happen to have a long chain of `then` calls, you can put an error handler in the very last one, and it will act like the `catch` clause in a try-catch statement.

```JavaScript
Promise.reject("BLAAAARG!! üò°üí¢")
  .then(
    () => console.log("Success ... but is it?")
    /* ü§∑‚Äç‚ôÄÔ∏è no error handler here ü§∑‚Äç‚ôÇÔ∏è */
  )
  .then(
    () => console.log("Will this ever get called?"),
    (error) => console.log("Second error handler: " + error)
  )
```

The previous example prints out this:

```
Second error handler: BLAAAARG!! üò°üí¢
```

So, this works pretty well.  That said, the only complaint I have is that having a `then` with **two** callbacks is kind of a pain to read, am I right?

It's so easy to miss that little comma at the end of your success handler.  And if you have curly braces&mdash;I don't know about you, but I always have to double-check and tripple-check, and I'll still miss a } from time to time.

Well, the JavaScript people seemed to think this was a problem as well, so they introduced two new methods to the `Promise` class, which are basically fancy wrappers for `then`.

The first is called `catch`, and it does literally what you think it should&mdash;it acts like the `catch` clause in a try-catch statement.  And if you need to, you can even tack a `then` clause on the end (afterwards), because the `catch` method will handle the error and return a new `Promise`.

```JavaScript
Promise.reject("BLAAAARG!! üò°üí¢")
  .then(
    () => console.log("This never gets seen.")
  )
  .then(
    () => console.log("This never gets seen, either.")
  )
  .catch(
    (error) => console.log("Error: " + error)
  )
```

The other new method is called `finally` and it also does exactly what you'd expect it to do.  Your `finally` callback is **guaranteed** to get called, whether there is an error or not.

```JavaScript
Promise.reject("Very mad")
  .then(_ => console.log("Never gets called"))
  .finally(_ => console.log("üíØ Guaranteed to get called üíØ"))
  .then(_ => console.log("Never gets called, either"))
  .catch(error => console.log("Error: " + error));
```

> ‚úã Note that the callback for the `finally` method takes no parameters.  So there is literally no way to tell if an error happened or not.

The previous example prints out this:

```
üíØ Guaranteed to get called üíØ
Error: Very mad
```

And the really cool thing is that because `Promises` allow you to have an asynchronous operation in one place and do all the handling in another place, You can nest your function calls as deep as you like, and have a single `.catch()` at the top-most function.  This keeps everything super clean.

```JavaScript
function funcOne() {
  return funcTwo
    .then( ... );
}

function funcTwo() {
  return foo()
    .then( ... );
}

funcOne()
  .then(result => 
    document.querySelector(".report").innerHTML = result;
  );
  .catch(error => 
    document.querySelector(".error").innerHTML = error;
  )
  .finally(_ =>
    console.log("Moving along...");
  );
```

So much more intentional.  So much easier to read.

# Exception handling

You might be asking yourself, what happens if my code throws an exception inside my `then` method's resolve callback?

```JavaScript
foo()
  .then(() => {
    throw new Error("Yeeeet! üí¢"); // üëà What happens here?
  })
```

You might be tempted to add an an error callback, like so:

```JavaScript
foo()
  .then(() => {
      throw new Error("Yeeeet! üí¢"); // üëà What happens here?
    },
    (err) => console.error(err);
  ) // ‚òù Will this work?
```

This won't work, because your reject callback is for the <u>previous `Promise`</u>, not the current one.  In order to handle any exceptions, you'd need a <u>second</u> `then` clause, or (better yet) you'd need to add a `catch`.

This will work just fine:

```JavaScript
foo()
  .then(() => {
      throw new Error("Yeeeet! üí¢");
    },
  )
  .catch(err =>
    console.error(err)  // üëà All exceptions get handled here.
  )
```

# Real-world example

Ok, now with all that in mind, let's take a look at a real-world example using a public API.  We're going to use another JavaScript function, called `fetch`, which (aptly named) is used for fetching data using REST.  The `fetch` function is a good example of promises, because it's very low-level&mdash;and because it is so low level, it requires us to do two asynchronous calls back to back:

1. The first call is to perform the REST request.
2. The second call is to retrieve all of the data in the response, which for really long requests can come in chunks and can take a long time.

The API we're going to hit is the Star Wars API (called "SWAPI", for short).  For more infomration about this API, you can go to [swapi.dev](https://swapi.dev/).

We're going to go to the `people` endpoint, and fetch the first ten Star Wars characters from their database, and print them out.

The `fetch` function is pretty easy to use.  You just pass in a URL, and it does a `GET`.  The return value is a `Promise` that contains response object, which tells you how the request went.

```JavaScript
fetch("https://someurl.com/some/path")
  .then(response => {
    // Check for errors and stuff
  })
```

Once you have a response, you have to check the status code. If the request was successful, it'll be 200, which is the HTTP status code for "Ok".  It's probably easier to just throw an exception if it's not a 200, that way the caller can deal with the problem.

Once you've verified the status code, you have to load the JSON.  This can take a long time, so JavaScript offloads that parsing task to the browser, and you get a promise to let you know when the parsing is complete.

```JavaScript
fetch('https://swapi.dev/api/people/')
  .then((response) => {
    if (response.status !== 200) {
      throw new Error(`${response.status} ${response.statusMessage}`);
    }

    return response.json(); // üëà return the next promise
  })
  .then((data) => 
    data.results.forEach((item) => console.log(item.name))
  )
  .catch(error => 
    console.error(error)
  );
```

And when you run it, you get the first page of results:

```
Luke Skywalker
C-3PO
R2-D2
Darth Vader
Leia Organa
Owen Lars
Beru Whitesun lars
R5-D4
Biggs Darklighter
Obi-Wan Kenobi
```

LOL, R5-D4 ... what a cut-up!  Always the life of a party.  

Not sure where my man Jar Jar Binks went, though.  "Misa thinkin' issa onna nother page!"

Enough of that.

# Conclusion

So this was a pretty in-depth article.  I don't expect the whole thing to make sense unless you've spent a lot of time working with promises.  All of these exapmles will run, so open up your console window, and paste them into your browser one by one.  The best way to learn is by experimenting.

And even though this pattern is a little outdated, it's still used all over the place.  On top of that, people are still getting used to `async` and `await`, which can be a bit of a mystery if you haven't taken the time to read up.
